### PR TITLE
Fix golint issue and remove unnecessary test/files

### PR DESCRIPTION
**Pull request by on99**

### CODE REVIEW

**Comment by raphael** [comment]
This is great! Do you think we could leave the generated code committed though? While it's true that it's not required it makes it easy to see what has changed since the last time it was generated. It is also a nice way to do a quick sanity check before pushing changes to the code generation algorithms. Thank you!

**Comment by on99** [comment]
Yes you are right! Can I also update the generator so the permission of files it generates is 0644? It's 0755 now but we do not need source files to be excutable.

**Comment by on99** [comment]
Rebased and pushed. Thank you @raphael  for review!

**Comment by raphael** [comment]
LGTM, thanks!

**Pull request merged**
