### PR TITLE
Add Metadata

### PR DESCRIPTION
**Pull request by bketelsen**
Added Metadata to many of the base DSL types to allow for key/value pairs to be attached to most of the nodes on the DSL tree.

UseCase: In custom generators I need the ability to annotate things that aren't strictly DSL related.

### CODE REVIEW

**Comment by bketelsen** [comment]
I think the lint checks are failing because goimports has a problem with goregen.  goimports removes the import for goregen for some reason.

**Comment by bketelsen** [comment]
woot passing tests.  Must be a goimports bug.  Strange.

**Comment by on99** [comment]
Import name `goregen` does not match the package name `regen`.
It causes `gocode`, `godef`, `goimports` error.
So make sure they are the same.

**Comment by raphael** [comment]
Thank you, this is great!

**Pull request merged**
